// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sdk.proto

package sdk

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ChainCodeInfo 链码上存储的信息
type ChainCodeData struct {
	// 数据发送者ID
	SenderID string `protobuf:"bytes,1,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	// 数据接收者ID
	ReceiverID string `protobuf:"bytes,2,opt,name=ReceiverID,proto3" json:"ReceiverID,omitempty"`
	// 完成一次信息查询操作的唯一标识
	FlowID string `protobuf:"bytes,3,opt,name=FlowID,proto3" json:"FlowID,omitempty"`
	// Type:是四个rpc service中的具体步骤
	RType int32 `protobuf:"varint,4,opt,name=RType,proto3" json:"RType,omitempty"`
	// hdfs path 文件存储平台地址：内容加密
	FilePath string `protobuf:"bytes,5,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	// path hash 路径的hash值：保证数据一致性
	FileHash             string   `protobuf:"bytes,6,opt,name=FileHash,proto3" json:"FileHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainCodeData) Reset()         { *m = ChainCodeData{} }
func (m *ChainCodeData) String() string { return proto.CompactTextString(m) }
func (*ChainCodeData) ProtoMessage()    {}
func (*ChainCodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{0}
}

func (m *ChainCodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainCodeData.Unmarshal(m, b)
}
func (m *ChainCodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainCodeData.Marshal(b, m, deterministic)
}
func (m *ChainCodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainCodeData.Merge(m, src)
}
func (m *ChainCodeData) XXX_Size() int {
	return xxx_messageInfo_ChainCodeData.Size(m)
}
func (m *ChainCodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainCodeData.DiscardUnknown(m)
}

var xxx_messageInfo_ChainCodeData proto.InternalMessageInfo

func (m *ChainCodeData) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *ChainCodeData) GetReceiverID() string {
	if m != nil {
		return m.ReceiverID
	}
	return ""
}

func (m *ChainCodeData) GetFlowID() string {
	if m != nil {
		return m.FlowID
	}
	return ""
}

func (m *ChainCodeData) GetRType() int32 {
	if m != nil {
		return m.RType
	}
	return 0
}

func (m *ChainCodeData) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *ChainCodeData) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

// SaveInfo 请求
type SaveInfoRequest struct {
	Data                 *ChainCodeData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveInfoRequest) Reset()         { *m = SaveInfoRequest{} }
func (m *SaveInfoRequest) String() string { return proto.CompactTextString(m) }
func (*SaveInfoRequest) ProtoMessage()    {}
func (*SaveInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{1}
}

func (m *SaveInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveInfoRequest.Unmarshal(m, b)
}
func (m *SaveInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveInfoRequest.Marshal(b, m, deterministic)
}
func (m *SaveInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveInfoRequest.Merge(m, src)
}
func (m *SaveInfoRequest) XXX_Size() int {
	return xxx_messageInfo_SaveInfoRequest.Size(m)
}
func (m *SaveInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveInfoRequest proto.InternalMessageInfo

func (m *SaveInfoRequest) GetData() *ChainCodeData {
	if m != nil {
		return m.Data
	}
	return nil
}

// SaveInfo resp
type SaveInfoResponse struct {
	Data                 int32    `protobuf:"varint,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveInfoResponse) Reset()         { *m = SaveInfoResponse{} }
func (m *SaveInfoResponse) String() string { return proto.CompactTextString(m) }
func (*SaveInfoResponse) ProtoMessage()    {}
func (*SaveInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{2}
}

func (m *SaveInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveInfoResponse.Unmarshal(m, b)
}
func (m *SaveInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveInfoResponse.Marshal(b, m, deterministic)
}
func (m *SaveInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveInfoResponse.Merge(m, src)
}
func (m *SaveInfoResponse) XXX_Size() int {
	return xxx_messageInfo_SaveInfoResponse.Size(m)
}
func (m *SaveInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveInfoResponse proto.InternalMessageInfo

func (m *SaveInfoResponse) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *SaveInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetInfo 请求
type GetInfoRequest struct {
	// 完成一次信息查询操作的唯一标识
	FlowId string `protobuf:"bytes,1,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	// 每次请求数据的具体步骤
	RType                int32    `protobuf:"varint,2,opt,name=rType,proto3" json:"rType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{3}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *GetInfoRequest) GetRType() int32 {
	if m != nil {
		return m.RType
	}
	return 0
}

// GetInfo resp
type GetInfoResponse struct {
	Data                 []*ChainCodeData `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{4}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetData() []*ChainCodeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type InvokeRequest struct {
	// chainCode 链码名称
	ChainCode string `protobuf:"bytes,1,opt,name=ChainCode,proto3" json:"ChainCode,omitempty"`
	// 调用的func name
	FuncName string `protobuf:"bytes,2,opt,name=FuncName,proto3" json:"FuncName,omitempty"`
	// args 参数
	Args                 []string `protobuf:"bytes,3,rep,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{5}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetChainCode() string {
	if m != nil {
		return m.ChainCode
	}
	return ""
}

func (m *InvokeRequest) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *InvokeRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type InvokeResponse struct {
	// code status
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// message
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	// payload info
	PayLoad              string   `protobuf:"bytes,3,opt,name=PayLoad,proto3" json:"PayLoad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70decb0fb6f436df, []int{6}
}

func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (m *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(m, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *InvokeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InvokeResponse) GetPayLoad() string {
	if m != nil {
		return m.PayLoad
	}
	return ""
}

func init() {
	proto.RegisterType((*ChainCodeData)(nil), "ChainCodeData")
	proto.RegisterType((*SaveInfoRequest)(nil), "SaveInfoRequest")
	proto.RegisterType((*SaveInfoResponse)(nil), "SaveInfoResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "GetInfoResponse")
	proto.RegisterType((*InvokeRequest)(nil), "InvokeRequest")
	proto.RegisterType((*InvokeResponse)(nil), "InvokeResponse")
}

func init() { proto.RegisterFile("sdk.proto", fileDescriptor_70decb0fb6f436df) }

var fileDescriptor_70decb0fb6f436df = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6b, 0xe2, 0x40,
	0x18, 0x26, 0xc6, 0x44, 0xf3, 0x2e, 0x46, 0x77, 0x58, 0x96, 0x10, 0x96, 0x45, 0x72, 0x72, 0x61,
	0x99, 0x05, 0x97, 0xbd, 0x2e, 0x2d, 0x06, 0xdb, 0xd0, 0x0f, 0x64, 0xec, 0xa1, 0x97, 0x1e, 0xa6,
	0x66, 0xaa, 0xa2, 0xcd, 0xd8, 0x4c, 0xb4, 0xf8, 0x2b, 0xfa, 0x5b, 0xfa, 0x0f, 0x4b, 0x26, 0x33,
	0x89, 0xb1, 0x78, 0xcb, 0x33, 0xcf, 0xbc, 0xf3, 0x7c, 0xbc, 0x01, 0x47, 0xc4, 0x2b, 0xbc, 0x49,
	0x79, 0xc6, 0x83, 0x77, 0x03, 0x3a, 0xa3, 0x05, 0x5d, 0x26, 0x23, 0x1e, 0xb3, 0x90, 0x66, 0x14,
	0xf9, 0xd0, 0x9e, 0xb2, 0x24, 0x66, 0x69, 0x14, 0x7a, 0x46, 0xdf, 0x18, 0x38, 0xa4, 0xc4, 0xe8,
	0x27, 0x00, 0x61, 0x33, 0xb6, 0xdc, 0x49, 0xb6, 0x21, 0xd9, 0x83, 0x13, 0xf4, 0x1d, 0xec, 0xf1,
	0x9a, 0xbf, 0x46, 0xa1, 0x67, 0x4a, 0x4e, 0x21, 0xf4, 0x0d, 0x2c, 0x72, 0xb7, 0xdf, 0x30, 0xaf,
	0xd9, 0x37, 0x06, 0x16, 0x29, 0x40, 0xae, 0x34, 0x5e, 0xae, 0xd9, 0x84, 0x66, 0x0b, 0xcf, 0x2a,
	0x94, 0x34, 0xd6, 0xdc, 0x25, 0x15, 0x0b, 0xcf, 0xae, 0xb8, 0x1c, 0x07, 0xff, 0xa0, 0x3b, 0xa5,
	0x3b, 0x16, 0x25, 0x4f, 0x9c, 0xb0, 0x97, 0x2d, 0x13, 0x19, 0x0a, 0xa0, 0x99, 0x9b, 0x97, 0x86,
	0xbf, 0x0c, 0x5d, 0x5c, 0x8b, 0x44, 0x24, 0x17, 0x9c, 0x41, 0xaf, 0x1a, 0x13, 0x1b, 0x9e, 0x08,
	0x86, 0xd0, 0xc1, 0x9c, 0x55, 0xdc, 0x43, 0x1e, 0xb4, 0x6e, 0x98, 0x10, 0x74, 0xce, 0x54, 0x42,
	0x0d, 0x83, 0xff, 0xe0, 0x5e, 0xb0, 0xec, 0x50, 0x57, 0x07, 0x8e, 0x55, 0x55, 0x0a, 0xe5, 0x81,
	0x53, 0x19, 0xb8, 0x51, 0x04, 0x96, 0x20, 0x37, 0x5e, 0xce, 0x2b, 0x03, 0x95, 0x71, 0xf3, 0xa4,
	0xf1, 0x07, 0xe8, 0x44, 0xc9, 0x8e, 0xaf, 0x98, 0x56, 0xfd, 0x01, 0x4e, 0x79, 0x4f, 0x09, 0x57,
	0x07, 0xb2, 0xba, 0x6d, 0x32, 0xbb, 0xa5, 0xcf, 0x3a, 0x40, 0x89, 0xf3, 0xbc, 0xe7, 0xe9, 0x5c,
	0x78, 0x66, 0xdf, 0x1c, 0x38, 0x44, 0x7e, 0x07, 0xf7, 0xe0, 0xea, 0xe7, 0xab, 0x56, 0xca, 0xa7,
	0x2d, 0x22, 0xbf, 0x4f, 0xb7, 0x92, 0x33, 0x13, 0xba, 0xbf, 0xe6, 0x34, 0x56, 0x5b, 0xd7, 0x70,
	0xf8, 0x66, 0x80, 0x39, 0x0d, 0xaf, 0xd0, 0x1f, 0x68, 0xeb, 0xe6, 0x51, 0x0f, 0x1f, 0xed, 0xce,
	0xff, 0x8a, 0x3f, 0xad, 0xe5, 0x37, 0xb4, 0x54, 0x51, 0xa8, 0x8b, 0xeb, 0x95, 0xfb, 0x3d, 0x7c,
	0xdc, 0xe1, 0x2f, 0xb0, 0x8b, 0x00, 0xc8, 0xc5, 0xb5, 0xa2, 0xfc, 0x2e, 0xae, 0x27, 0x7b, 0xb4,
	0xe5, 0x5f, 0xff, 0xf7, 0x23, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x40, 0x56, 0xa8, 0x02, 0x03, 0x00,
	0x00,
}
