// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetCrySqlRequest sql查询请求
type GetCrySqlRequest struct {
	ConsumerId string `protobuf:"bytes,1,opt,name=ConsumerId,proto3" json:"ConsumerId,omitempty"`
	ProviderId string `protobuf:"bytes,2,opt,name=ProviderId,proto3" json:"ProviderId,omitempty"`
	// 查询sql
	Sql string `protobuf:"bytes,3,opt,name=Sql,proto3" json:"Sql,omitempty"`
	// dumpID 数据集的id
	DumpId string `protobuf:"bytes,4,opt,name=DumpId,proto3" json:"DumpId,omitempty"`
	// 查询描述，即数据集描述
	Text                 string   `protobuf:"bytes,5,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCrySqlRequest) Reset()         { *m = GetCrySqlRequest{} }
func (m *GetCrySqlRequest) String() string { return proto.CompactTextString(m) }
func (*GetCrySqlRequest) ProtoMessage()    {}
func (*GetCrySqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *GetCrySqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCrySqlRequest.Unmarshal(m, b)
}
func (m *GetCrySqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCrySqlRequest.Marshal(b, m, deterministic)
}
func (m *GetCrySqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCrySqlRequest.Merge(m, src)
}
func (m *GetCrySqlRequest) XXX_Size() int {
	return xxx_messageInfo_GetCrySqlRequest.Size(m)
}
func (m *GetCrySqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCrySqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCrySqlRequest proto.InternalMessageInfo

func (m *GetCrySqlRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *GetCrySqlRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *GetCrySqlRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *GetCrySqlRequest) GetDumpId() string {
	if m != nil {
		return m.DumpId
	}
	return ""
}

func (m *GetCrySqlRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetCrySqlResponse struct {
	// 查询sql的整个flow的标识
	FlowId string `protobuf:"bytes,1,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	// 链码返回的txID
	TxId string `protobuf:"bytes,2,opt,name=TxId,proto3" json:"TxId,omitempty"`
	// Code 状态码
	Status int32 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// Message
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCrySqlResponse) Reset()         { *m = GetCrySqlResponse{} }
func (m *GetCrySqlResponse) String() string { return proto.CompactTextString(m) }
func (*GetCrySqlResponse) ProtoMessage()    {}
func (*GetCrySqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *GetCrySqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCrySqlResponse.Unmarshal(m, b)
}
func (m *GetCrySqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCrySqlResponse.Marshal(b, m, deterministic)
}
func (m *GetCrySqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCrySqlResponse.Merge(m, src)
}
func (m *GetCrySqlResponse) XXX_Size() int {
	return xxx_messageInfo_GetCrySqlResponse.Size(m)
}
func (m *GetCrySqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCrySqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCrySqlResponse proto.InternalMessageInfo

func (m *GetCrySqlResponse) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *GetCrySqlResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *GetCrySqlResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetCrySqlResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetDeResRequest struct {
	ConsumerId string `protobuf:"bytes,1,opt,name=ConsumerId,proto3" json:"ConsumerId,omitempty"`
	ProviderId string `protobuf:"bytes,2,opt,name=ProviderId,proto3" json:"ProviderId,omitempty"`
	//  string CrySqlPath = 3;
	FlowId               string   `protobuf:"bytes,4,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeResRequest) Reset()         { *m = GetDeResRequest{} }
func (m *GetDeResRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeResRequest) ProtoMessage()    {}
func (*GetDeResRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *GetDeResRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeResRequest.Unmarshal(m, b)
}
func (m *GetDeResRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeResRequest.Marshal(b, m, deterministic)
}
func (m *GetDeResRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeResRequest.Merge(m, src)
}
func (m *GetDeResRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeResRequest.Size(m)
}
func (m *GetDeResRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeResRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeResRequest proto.InternalMessageInfo

func (m *GetDeResRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *GetDeResRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *GetDeResRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

type GetDeResResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeResResponse) Reset()         { *m = GetDeResResponse{} }
func (m *GetDeResResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeResResponse) ProtoMessage()    {}
func (*GetDeResResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *GetDeResResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeResResponse.Unmarshal(m, b)
}
func (m *GetDeResResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeResResponse.Marshal(b, m, deterministic)
}
func (m *GetDeResResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeResResponse.Merge(m, src)
}
func (m *GetDeResResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeResResponse.Size(m)
}
func (m *GetDeResResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeResResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeResResponse proto.InternalMessageInfo

type CrySqlRequest struct {
	ConsumerId string `protobuf:"bytes,1,opt,name=ConsumerId,proto3" json:"ConsumerId,omitempty"`
	ProviderId string `protobuf:"bytes,2,opt,name=ProviderId,proto3" json:"ProviderId,omitempty"`
	//  string CrySqlPath = 3;
	FlowId               string   `protobuf:"bytes,4,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrySqlRequest) Reset()         { *m = CrySqlRequest{} }
func (m *CrySqlRequest) String() string { return proto.CompactTextString(m) }
func (*CrySqlRequest) ProtoMessage()    {}
func (*CrySqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *CrySqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrySqlRequest.Unmarshal(m, b)
}
func (m *CrySqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrySqlRequest.Marshal(b, m, deterministic)
}
func (m *CrySqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrySqlRequest.Merge(m, src)
}
func (m *CrySqlRequest) XXX_Size() int {
	return xxx_messageInfo_CrySqlRequest.Size(m)
}
func (m *CrySqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrySqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrySqlRequest proto.InternalMessageInfo

func (m *CrySqlRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *CrySqlRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *CrySqlRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

type CrySqlResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrySqlResponse) Reset()         { *m = CrySqlResponse{} }
func (m *CrySqlResponse) String() string { return proto.CompactTextString(m) }
func (*CrySqlResponse) ProtoMessage()    {}
func (*CrySqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *CrySqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrySqlResponse.Unmarshal(m, b)
}
func (m *CrySqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrySqlResponse.Marshal(b, m, deterministic)
}
func (m *CrySqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrySqlResponse.Merge(m, src)
}
func (m *CrySqlResponse) XXX_Size() int {
	return xxx_messageInfo_CrySqlResponse.Size(m)
}
func (m *CrySqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrySqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrySqlResponse proto.InternalMessageInfo

type DeResRequest struct {
	ConsumerId string `protobuf:"bytes,1,opt,name=ConsumerId,proto3" json:"ConsumerId,omitempty"`
	ProviderId string `protobuf:"bytes,2,opt,name=ProviderId,proto3" json:"ProviderId,omitempty"`
	//  string DeResPath = 3;
	FlowId               string   `protobuf:"bytes,4,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeResRequest) Reset()         { *m = DeResRequest{} }
func (m *DeResRequest) String() string { return proto.CompactTextString(m) }
func (*DeResRequest) ProtoMessage()    {}
func (*DeResRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *DeResRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeResRequest.Unmarshal(m, b)
}
func (m *DeResRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeResRequest.Marshal(b, m, deterministic)
}
func (m *DeResRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeResRequest.Merge(m, src)
}
func (m *DeResRequest) XXX_Size() int {
	return xxx_messageInfo_DeResRequest.Size(m)
}
func (m *DeResRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeResRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeResRequest proto.InternalMessageInfo

func (m *DeResRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *DeResRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *DeResRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

type DeResResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeResResponse) Reset()         { *m = DeResResponse{} }
func (m *DeResResponse) String() string { return proto.CompactTextString(m) }
func (*DeResResponse) ProtoMessage()    {}
func (*DeResResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *DeResResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeResResponse.Unmarshal(m, b)
}
func (m *DeResResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeResResponse.Marshal(b, m, deterministic)
}
func (m *DeResResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeResResponse.Merge(m, src)
}
func (m *DeResResponse) XXX_Size() int {
	return xxx_messageInfo_DeResResponse.Size(m)
}
func (m *DeResResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeResResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeResResponse proto.InternalMessageInfo

//== operate dumpcc
type DumpInfoRequest struct {
	DumpId               string   `protobuf:"bytes,1,opt,name=DumpId,proto3" json:"DumpId,omitempty"`
	DumpName             string   `protobuf:"bytes,2,opt,name=DumpName,proto3" json:"DumpName,omitempty"`
	OwnerId              string   `protobuf:"bytes,3,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	DumpHash             string   `protobuf:"bytes,4,opt,name=DumpHash,proto3" json:"DumpHash,omitempty"`
	DumpFilePath         string   `protobuf:"bytes,5,opt,name=DumpFilePath,proto3" json:"DumpFilePath,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Keywords             []string `protobuf:"bytes,7,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=Description,proto3" json:"Description,omitempty"`
	Tables               []*Table `protobuf:"bytes,9,rep,name=Tables,proto3" json:"Tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpInfoRequest) Reset()         { *m = DumpInfoRequest{} }
func (m *DumpInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DumpInfoRequest) ProtoMessage()    {}
func (*DumpInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *DumpInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpInfoRequest.Unmarshal(m, b)
}
func (m *DumpInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpInfoRequest.Marshal(b, m, deterministic)
}
func (m *DumpInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpInfoRequest.Merge(m, src)
}
func (m *DumpInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DumpInfoRequest.Size(m)
}
func (m *DumpInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpInfoRequest proto.InternalMessageInfo

func (m *DumpInfoRequest) GetDumpId() string {
	if m != nil {
		return m.DumpId
	}
	return ""
}

func (m *DumpInfoRequest) GetDumpName() string {
	if m != nil {
		return m.DumpName
	}
	return ""
}

func (m *DumpInfoRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *DumpInfoRequest) GetDumpHash() string {
	if m != nil {
		return m.DumpHash
	}
	return ""
}

func (m *DumpInfoRequest) GetDumpFilePath() string {
	if m != nil {
		return m.DumpFilePath
	}
	return ""
}

func (m *DumpInfoRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DumpInfoRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *DumpInfoRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DumpInfoRequest) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

type Table struct {
	TableUSName          string        `protobuf:"bytes,1,opt,name=TableUSName,proto3" json:"TableUSName,omitempty"`
	TableCNName          string        `protobuf:"bytes,2,opt,name=TableCNName,proto3" json:"TableCNName,omitempty"`
	TableType            string        `protobuf:"bytes,3,opt,name=TableType,proto3" json:"TableType,omitempty"`
	TableComments        string        `protobuf:"bytes,4,opt,name=TableComments,proto3" json:"TableComments,omitempty"`
	DataType             string        `protobuf:"bytes,5,opt,name=DataType,proto3" json:"DataType,omitempty"`
	DataPrice            string        `protobuf:"bytes,6,opt,name=DataPrice,proto3" json:"DataPrice,omitempty"`
	TableDataExamples    []string      `protobuf:"bytes,7,rep,name=TableDataExamples,proto3" json:"TableDataExamples,omitempty"`
	TableFields          []*TableField `protobuf:"bytes,8,rep,name=TableFields,proto3" json:"TableFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{9}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetTableUSName() string {
	if m != nil {
		return m.TableUSName
	}
	return ""
}

func (m *Table) GetTableCNName() string {
	if m != nil {
		return m.TableCNName
	}
	return ""
}

func (m *Table) GetTableType() string {
	if m != nil {
		return m.TableType
	}
	return ""
}

func (m *Table) GetTableComments() string {
	if m != nil {
		return m.TableComments
	}
	return ""
}

func (m *Table) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Table) GetDataPrice() string {
	if m != nil {
		return m.DataPrice
	}
	return ""
}

func (m *Table) GetTableDataExamples() []string {
	if m != nil {
		return m.TableDataExamples
	}
	return nil
}

func (m *Table) GetTableFields() []*TableField {
	if m != nil {
		return m.TableFields
	}
	return nil
}

type TableField struct {
	Key                  bool     `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	USName               string   `protobuf:"bytes,2,opt,name=USName,proto3" json:"USName,omitempty"`
	CNName               string   `protobuf:"bytes,3,opt,name=CNName,proto3" json:"CNName,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Length               string   `protobuf:"bytes,5,opt,name=Length,proto3" json:"Length,omitempty"`
	Precision            string   `protobuf:"bytes,6,opt,name=Precision,proto3" json:"Precision,omitempty"`
	Comments             string   `protobuf:"bytes,7,opt,name=Comments,proto3" json:"Comments,omitempty"`
	Default              string   `protobuf:"bytes,8,opt,name=Default,proto3" json:"Default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableField) Reset()         { *m = TableField{} }
func (m *TableField) String() string { return proto.CompactTextString(m) }
func (*TableField) ProtoMessage()    {}
func (*TableField) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{10}
}

func (m *TableField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableField.Unmarshal(m, b)
}
func (m *TableField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableField.Marshal(b, m, deterministic)
}
func (m *TableField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableField.Merge(m, src)
}
func (m *TableField) XXX_Size() int {
	return xxx_messageInfo_TableField.Size(m)
}
func (m *TableField) XXX_DiscardUnknown() {
	xxx_messageInfo_TableField.DiscardUnknown(m)
}

var xxx_messageInfo_TableField proto.InternalMessageInfo

func (m *TableField) GetKey() bool {
	if m != nil {
		return m.Key
	}
	return false
}

func (m *TableField) GetUSName() string {
	if m != nil {
		return m.USName
	}
	return ""
}

func (m *TableField) GetCNName() string {
	if m != nil {
		return m.CNName
	}
	return ""
}

func (m *TableField) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TableField) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *TableField) GetPrecision() string {
	if m != nil {
		return m.Precision
	}
	return ""
}

func (m *TableField) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *TableField) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

type KeyDumpInfoRequest struct {
	DumpId               string   `protobuf:"bytes,1,opt,name=DumpId,proto3" json:"DumpId,omitempty"`
	TableName            string   `protobuf:"bytes,3,opt,name=TableName,proto3" json:"TableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyDumpInfoRequest) Reset()         { *m = KeyDumpInfoRequest{} }
func (m *KeyDumpInfoRequest) String() string { return proto.CompactTextString(m) }
func (*KeyDumpInfoRequest) ProtoMessage()    {}
func (*KeyDumpInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{11}
}

func (m *KeyDumpInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyDumpInfoRequest.Unmarshal(m, b)
}
func (m *KeyDumpInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyDumpInfoRequest.Marshal(b, m, deterministic)
}
func (m *KeyDumpInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDumpInfoRequest.Merge(m, src)
}
func (m *KeyDumpInfoRequest) XXX_Size() int {
	return xxx_messageInfo_KeyDumpInfoRequest.Size(m)
}
func (m *KeyDumpInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDumpInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDumpInfoRequest proto.InternalMessageInfo

func (m *KeyDumpInfoRequest) GetDumpId() string {
	if m != nil {
		return m.DumpId
	}
	return ""
}

func (m *KeyDumpInfoRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type QueryDumpInfoByIdRequest struct {
	DumpId               string   `protobuf:"bytes,1,opt,name=DumpId,proto3" json:"DumpId,omitempty"`
	TablePageIndex       int64    `protobuf:"varint,3,opt,name=TablePageIndex,proto3" json:"TablePageIndex,omitempty"`
	TablePageSize        int64    `protobuf:"varint,4,opt,name=TablePageSize,proto3" json:"TablePageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDumpInfoByIdRequest) Reset()         { *m = QueryDumpInfoByIdRequest{} }
func (m *QueryDumpInfoByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDumpInfoByIdRequest) ProtoMessage()    {}
func (*QueryDumpInfoByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{12}
}

func (m *QueryDumpInfoByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDumpInfoByIdRequest.Unmarshal(m, b)
}
func (m *QueryDumpInfoByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDumpInfoByIdRequest.Marshal(b, m, deterministic)
}
func (m *QueryDumpInfoByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDumpInfoByIdRequest.Merge(m, src)
}
func (m *QueryDumpInfoByIdRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDumpInfoByIdRequest.Size(m)
}
func (m *QueryDumpInfoByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDumpInfoByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDumpInfoByIdRequest proto.InternalMessageInfo

func (m *QueryDumpInfoByIdRequest) GetDumpId() string {
	if m != nil {
		return m.DumpId
	}
	return ""
}

func (m *QueryDumpInfoByIdRequest) GetTablePageIndex() int64 {
	if m != nil {
		return m.TablePageIndex
	}
	return 0
}

func (m *QueryDumpInfoByIdRequest) GetTablePageSize() int64 {
	if m != nil {
		return m.TablePageSize
	}
	return 0
}

type QueryDumpInfoByKeywordsRequest struct {
	Keywords             string   `protobuf:"bytes,1,opt,name=Keywords,proto3" json:"Keywords,omitempty"`
	DumpPageIndex        int64    `protobuf:"varint,2,opt,name=DumpPageIndex,proto3" json:"DumpPageIndex,omitempty"`
	DumpPageSize         int64    `protobuf:"varint,3,opt,name=DumpPageSize,proto3" json:"DumpPageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDumpInfoByKeywordsRequest) Reset()         { *m = QueryDumpInfoByKeywordsRequest{} }
func (m *QueryDumpInfoByKeywordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDumpInfoByKeywordsRequest) ProtoMessage()    {}
func (*QueryDumpInfoByKeywordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{13}
}

func (m *QueryDumpInfoByKeywordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDumpInfoByKeywordsRequest.Unmarshal(m, b)
}
func (m *QueryDumpInfoByKeywordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDumpInfoByKeywordsRequest.Marshal(b, m, deterministic)
}
func (m *QueryDumpInfoByKeywordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDumpInfoByKeywordsRequest.Merge(m, src)
}
func (m *QueryDumpInfoByKeywordsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDumpInfoByKeywordsRequest.Size(m)
}
func (m *QueryDumpInfoByKeywordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDumpInfoByKeywordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDumpInfoByKeywordsRequest proto.InternalMessageInfo

func (m *QueryDumpInfoByKeywordsRequest) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *QueryDumpInfoByKeywordsRequest) GetDumpPageIndex() int64 {
	if m != nil {
		return m.DumpPageIndex
	}
	return 0
}

func (m *QueryDumpInfoByKeywordsRequest) GetDumpPageSize() int64 {
	if m != nil {
		return m.DumpPageSize
	}
	return 0
}

type QueryRecentlyDumpInfoRequest struct {
	DumpPageIndex        int64    `protobuf:"varint,1,opt,name=DumpPageIndex,proto3" json:"DumpPageIndex,omitempty"`
	DumpPageSize         int64    `protobuf:"varint,2,opt,name=DumpPageSize,proto3" json:"DumpPageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRecentlyDumpInfoRequest) Reset()         { *m = QueryRecentlyDumpInfoRequest{} }
func (m *QueryRecentlyDumpInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecentlyDumpInfoRequest) ProtoMessage()    {}
func (*QueryRecentlyDumpInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{14}
}

func (m *QueryRecentlyDumpInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRecentlyDumpInfoRequest.Unmarshal(m, b)
}
func (m *QueryRecentlyDumpInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRecentlyDumpInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryRecentlyDumpInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecentlyDumpInfoRequest.Merge(m, src)
}
func (m *QueryRecentlyDumpInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRecentlyDumpInfoRequest.Size(m)
}
func (m *QueryRecentlyDumpInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecentlyDumpInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecentlyDumpInfoRequest proto.InternalMessageInfo

func (m *QueryRecentlyDumpInfoRequest) GetDumpPageIndex() int64 {
	if m != nil {
		return m.DumpPageIndex
	}
	return 0
}

func (m *QueryRecentlyDumpInfoRequest) GetDumpPageSize() int64 {
	if m != nil {
		return m.DumpPageSize
	}
	return 0
}

type GetStepNumberRequest struct {
	FlowId               string   `protobuf:"bytes,1,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStepNumberRequest) Reset()         { *m = GetStepNumberRequest{} }
func (m *GetStepNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetStepNumberRequest) ProtoMessage()    {}
func (*GetStepNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{15}
}

func (m *GetStepNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStepNumberRequest.Unmarshal(m, b)
}
func (m *GetStepNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStepNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetStepNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStepNumberRequest.Merge(m, src)
}
func (m *GetStepNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetStepNumberRequest.Size(m)
}
func (m *GetStepNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStepNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStepNumberRequest proto.InternalMessageInfo

func (m *GetStepNumberRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

type QueryPurchasedRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PageIndex            int64    `protobuf:"varint,2,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	PageSize             int64    `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPurchasedRequest) Reset()         { *m = QueryPurchasedRequest{} }
func (m *QueryPurchasedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPurchasedRequest) ProtoMessage()    {}
func (*QueryPurchasedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{16}
}

func (m *QueryPurchasedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPurchasedRequest.Unmarshal(m, b)
}
func (m *QueryPurchasedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPurchasedRequest.Marshal(b, m, deterministic)
}
func (m *QueryPurchasedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPurchasedRequest.Merge(m, src)
}
func (m *QueryPurchasedRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPurchasedRequest.Size(m)
}
func (m *QueryPurchasedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPurchasedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPurchasedRequest proto.InternalMessageInfo

func (m *QueryPurchasedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryPurchasedRequest) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *QueryPurchasedRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type QueryOwnerDumpInfoRequest struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	DumpPageIndex        int64    `protobuf:"varint,2,opt,name=DumpPageIndex,proto3" json:"DumpPageIndex,omitempty"`
	DumpPageSize         int64    `protobuf:"varint,3,opt,name=DumpPageSize,proto3" json:"DumpPageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOwnerDumpInfoRequest) Reset()         { *m = QueryOwnerDumpInfoRequest{} }
func (m *QueryOwnerDumpInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOwnerDumpInfoRequest) ProtoMessage()    {}
func (*QueryOwnerDumpInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{17}
}

func (m *QueryOwnerDumpInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOwnerDumpInfoRequest.Unmarshal(m, b)
}
func (m *QueryOwnerDumpInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOwnerDumpInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryOwnerDumpInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnerDumpInfoRequest.Merge(m, src)
}
func (m *QueryOwnerDumpInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOwnerDumpInfoRequest.Size(m)
}
func (m *QueryOwnerDumpInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnerDumpInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnerDumpInfoRequest proto.InternalMessageInfo

func (m *QueryOwnerDumpInfoRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *QueryOwnerDumpInfoRequest) GetDumpPageIndex() int64 {
	if m != nil {
		return m.DumpPageIndex
	}
	return 0
}

func (m *QueryOwnerDumpInfoRequest) GetDumpPageSize() int64 {
	if m != nil {
		return m.DumpPageSize
	}
	return 0
}

type Response struct {
	Status               int64    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{18}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetStepNumberResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 int64    `protobuf:"varint,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStepNumberResponse) Reset()         { *m = GetStepNumberResponse{} }
func (m *GetStepNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GetStepNumberResponse) ProtoMessage()    {}
func (*GetStepNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{19}
}

func (m *GetStepNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStepNumberResponse.Unmarshal(m, b)
}
func (m *GetStepNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStepNumberResponse.Marshal(b, m, deterministic)
}
func (m *GetStepNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStepNumberResponse.Merge(m, src)
}
func (m *GetStepNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GetStepNumberResponse.Size(m)
}
func (m *GetStepNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStepNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStepNumberResponse proto.InternalMessageInfo

func (m *GetStepNumberResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetStepNumberResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetStepNumberResponse) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

// sql查询返回结果接口request
type ViewSqlResultRequest struct {
	FlowId               string   `protobuf:"bytes,1,opt,name=FlowId,proto3" json:"FlowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewSqlResultRequest) Reset()         { *m = ViewSqlResultRequest{} }
func (m *ViewSqlResultRequest) String() string { return proto.CompactTextString(m) }
func (*ViewSqlResultRequest) ProtoMessage()    {}
func (*ViewSqlResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{20}
}

func (m *ViewSqlResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSqlResultRequest.Unmarshal(m, b)
}
func (m *ViewSqlResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSqlResultRequest.Marshal(b, m, deterministic)
}
func (m *ViewSqlResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSqlResultRequest.Merge(m, src)
}
func (m *ViewSqlResultRequest) XXX_Size() int {
	return xxx_messageInfo_ViewSqlResultRequest.Size(m)
}
func (m *ViewSqlResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSqlResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSqlResultRequest proto.InternalMessageInfo

func (m *ViewSqlResultRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

// sql查询返回结果response
type ViewSqlResponse struct {
	// sql
	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	// 列名结果
	Cols []string `protobuf:"bytes,2,rep,name=Cols,proto3" json:"Cols,omitempty"`
	// row结果
	RowsData             []*RowsData `protobuf:"bytes,3,rep,name=RowsData,proto3" json:"RowsData,omitempty"`
	Status               int64       `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Message              string      `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ViewSqlResponse) Reset()         { *m = ViewSqlResponse{} }
func (m *ViewSqlResponse) String() string { return proto.CompactTextString(m) }
func (*ViewSqlResponse) ProtoMessage()    {}
func (*ViewSqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{21}
}

func (m *ViewSqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSqlResponse.Unmarshal(m, b)
}
func (m *ViewSqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSqlResponse.Marshal(b, m, deterministic)
}
func (m *ViewSqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSqlResponse.Merge(m, src)
}
func (m *ViewSqlResponse) XXX_Size() int {
	return xxx_messageInfo_ViewSqlResponse.Size(m)
}
func (m *ViewSqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSqlResponse proto.InternalMessageInfo

func (m *ViewSqlResponse) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *ViewSqlResponse) GetCols() []string {
	if m != nil {
		return m.Cols
	}
	return nil
}

func (m *ViewSqlResponse) GetRowsData() []*RowsData {
	if m != nil {
		return m.RowsData
	}
	return nil
}

func (m *ViewSqlResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ViewSqlResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// sql查询结果集
type RowsData struct {
	RowValue             []string `protobuf:"bytes,1,rep,name=RowValue,proto3" json:"RowValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowsData) Reset()         { *m = RowsData{} }
func (m *RowsData) String() string { return proto.CompactTextString(m) }
func (*RowsData) ProtoMessage()    {}
func (*RowsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{22}
}

func (m *RowsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowsData.Unmarshal(m, b)
}
func (m *RowsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowsData.Marshal(b, m, deterministic)
}
func (m *RowsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowsData.Merge(m, src)
}
func (m *RowsData) XXX_Size() int {
	return xxx_messageInfo_RowsData.Size(m)
}
func (m *RowsData) XXX_DiscardUnknown() {
	xxx_messageInfo_RowsData.DiscardUnknown(m)
}

var xxx_messageInfo_RowsData proto.InternalMessageInfo

func (m *RowsData) GetRowValue() []string {
	if m != nil {
		return m.RowValue
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCrySqlRequest)(nil), "GetCrySqlRequest")
	proto.RegisterType((*GetCrySqlResponse)(nil), "GetCrySqlResponse")
	proto.RegisterType((*GetDeResRequest)(nil), "GetDeResRequest")
	proto.RegisterType((*GetDeResResponse)(nil), "GetDeResResponse")
	proto.RegisterType((*CrySqlRequest)(nil), "CrySqlRequest")
	proto.RegisterType((*CrySqlResponse)(nil), "CrySqlResponse")
	proto.RegisterType((*DeResRequest)(nil), "DeResRequest")
	proto.RegisterType((*DeResResponse)(nil), "DeResResponse")
	proto.RegisterType((*DumpInfoRequest)(nil), "DumpInfoRequest")
	proto.RegisterType((*Table)(nil), "Table")
	proto.RegisterType((*TableField)(nil), "TableField")
	proto.RegisterType((*KeyDumpInfoRequest)(nil), "KeyDumpInfoRequest")
	proto.RegisterType((*QueryDumpInfoByIdRequest)(nil), "QueryDumpInfoByIdRequest")
	proto.RegisterType((*QueryDumpInfoByKeywordsRequest)(nil), "QueryDumpInfoByKeywordsRequest")
	proto.RegisterType((*QueryRecentlyDumpInfoRequest)(nil), "QueryRecentlyDumpInfoRequest")
	proto.RegisterType((*GetStepNumberRequest)(nil), "GetStepNumberRequest")
	proto.RegisterType((*QueryPurchasedRequest)(nil), "QueryPurchasedRequest")
	proto.RegisterType((*QueryOwnerDumpInfoRequest)(nil), "QueryOwnerDumpInfoRequest")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*GetStepNumberResponse)(nil), "GetStepNumberResponse")
	proto.RegisterType((*ViewSqlResultRequest)(nil), "ViewSqlResultRequest")
	proto.RegisterType((*ViewSqlResponse)(nil), "ViewSqlResponse")
	proto.RegisterType((*RowsData)(nil), "RowsData")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 1124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0x96, 0x13, 0x12, 0x92, 0x03, 0x09, 0x61, 0xba, 0xb0, 0xde, 0x68, 0x4b, 0x91, 0xb5, 0x45,
	0x5b, 0xb5, 0x3b, 0xad, 0xd8, 0xfe, 0x49, 0x95, 0x2a, 0x6d, 0x61, 0xa1, 0x94, 0x96, 0x4d, 0x1d,
	0xd8, 0xbb, 0x5e, 0x0c, 0xc9, 0x21, 0x58, 0x72, 0xe2, 0xe0, 0xb1, 0x09, 0xe9, 0x4d, 0x7b, 0xd5,
	0xeb, 0xed, 0x43, 0xb4, 0x8f, 0xd3, 0x67, 0xaa, 0xe6, 0xc7, 0xf6, 0xd8, 0x49, 0x80, 0x0b, 0xb4,
	0x77, 0x73, 0xbe, 0x99, 0x39, 0x3f, 0xdf, 0x1c, 0x7f, 0x33, 0x06, 0xe8, 0xb3, 0x88, 0xd1, 0x71,
	0x18, 0x44, 0x81, 0xf3, 0xce, 0x82, 0xd6, 0x21, 0x46, 0x7b, 0xe1, 0xb4, 0x7b, 0xe5, 0xbb, 0x78,
	0x15, 0x23, 0x8f, 0xc8, 0x16, 0xc0, 0x5e, 0x30, 0xe2, 0xf1, 0x10, 0xc3, 0xa3, 0xbe, 0x6d, 0x6d,
	0x5b, 0xcf, 0xeb, 0xae, 0x81, 0x88, 0xf9, 0x4e, 0x18, 0x5c, 0x7b, 0x7d, 0x39, 0x5f, 0x52, 0xf3,
	0x19, 0x42, 0x5a, 0x50, 0xee, 0x5e, 0xf9, 0x76, 0x59, 0x4e, 0x88, 0x21, 0xd9, 0x84, 0xea, 0x7e,
	0x3c, 0x1c, 0x1f, 0xf5, 0xed, 0x25, 0x09, 0x6a, 0x8b, 0x10, 0x58, 0x3a, 0xc5, 0x9b, 0xc8, 0xae,
	0x48, 0x54, 0x8e, 0x9d, 0x2b, 0x58, 0x37, 0x32, 0xe2, 0xe3, 0x60, 0xc4, 0x51, 0x38, 0x38, 0xf0,
	0x83, 0x49, 0x9a, 0x8e, 0xb6, 0xa4, 0x83, 0x9b, 0x34, 0x09, 0x39, 0x16, 0x6b, 0xbb, 0x11, 0x8b,
	0x62, 0x2e, 0x33, 0xa8, 0xb8, 0xda, 0x22, 0x36, 0x2c, 0xff, 0x82, 0x9c, 0xb3, 0x01, 0xea, 0x2c,
	0x12, 0xd3, 0xf1, 0x60, 0xed, 0x10, 0xa3, 0x7d, 0x74, 0x91, 0x3f, 0x14, 0x07, 0x59, 0xc2, 0x4b,
	0x66, 0xc2, 0x0e, 0x91, 0x7c, 0xeb, 0x50, 0xaa, 0x38, 0x67, 0x00, 0x8d, 0x87, 0x3d, 0x80, 0x45,
	0xc1, 0x5b, 0xd0, 0xcc, 0xf3, 0xea, 0x5c, 0xc0, 0xea, 0x7b, 0x29, 0x7b, 0x0d, 0x1a, 0xf9, 0x9a,
	0xff, 0x2e, 0xc1, 0x9a, 0x6c, 0x82, 0xd1, 0x45, 0x90, 0x04, 0xcf, 0xba, 0xc4, 0xca, 0x75, 0x49,
	0x1b, 0x6a, 0x62, 0x74, 0xc2, 0x86, 0xa8, 0x43, 0xa6, 0xb6, 0x38, 0xd4, 0x37, 0x93, 0x91, 0xcc,
	0x46, 0xf5, 0x5b, 0x62, 0x26, 0xbb, 0x7e, 0x64, 0xfc, 0x52, 0x27, 0x93, 0xda, 0xc4, 0x81, 0x55,
	0x31, 0x3e, 0xf0, 0x7c, 0xec, 0xb0, 0xe8, 0x52, 0xf7, 0x5f, 0x0e, 0x93, 0xad, 0xc5, 0x06, 0xdc,
	0xae, 0x6e, 0x97, 0x65, 0x6b, 0xb1, 0x01, 0x17, 0x3e, 0x8f, 0x71, 0x3a, 0x09, 0xc2, 0x3e, 0xb7,
	0x97, 0x25, 0x9e, 0xda, 0x64, 0x1b, 0x56, 0xf6, 0x91, 0xf7, 0x42, 0x6f, 0x1c, 0x79, 0xc1, 0xc8,
	0xae, 0x49, 0x97, 0x26, 0x44, 0xb6, 0xa0, 0x7a, 0xca, 0xce, 0x7d, 0xe4, 0x76, 0x7d, 0xbb, 0xfc,
	0x7c, 0x65, 0xb7, 0x4a, 0xa5, 0xe9, 0x6a, 0xd4, 0xf9, 0xb7, 0x04, 0x15, 0x39, 0x14, 0xbe, 0xe4,
	0xe0, 0xac, 0x2b, 0x8b, 0x56, 0x74, 0x98, 0x50, 0xba, 0x62, 0xef, 0xc4, 0xa0, 0xc5, 0x84, 0xc8,
	0x53, 0xa8, 0x4b, 0xf3, 0x74, 0x3a, 0x46, 0xcd, 0x4d, 0x06, 0x90, 0x67, 0xd0, 0x50, 0x8b, 0x83,
	0xe1, 0x10, 0x47, 0x11, 0xd7, 0x14, 0xe5, 0x41, 0xc9, 0x21, 0x8b, 0x98, 0x74, 0x51, 0xd1, 0x1c,
	0x6a, 0x5b, 0xf8, 0x17, 0xe3, 0x4e, 0xe8, 0xf5, 0xd0, 0xae, 0x2a, 0xff, 0x29, 0x40, 0x3e, 0x83,
	0x75, 0xe9, 0x4a, 0x20, 0xaf, 0x6f, 0xd8, 0x70, 0x2c, 0xca, 0x56, 0x94, 0xcd, 0x4e, 0x90, 0x17,
	0xba, 0x9a, 0x03, 0x0f, 0xfd, 0x3e, 0xb7, 0x6b, 0x92, 0x9e, 0x15, 0x9a, 0x61, 0xae, 0x39, 0xef,
	0xfc, 0x67, 0x01, 0x64, 0xb6, 0xd0, 0x9b, 0x63, 0x9c, 0x4a, 0x96, 0x6a, 0xae, 0x18, 0x8a, 0x4e,
	0xd2, 0xd4, 0x29, 0x62, 0xb4, 0x25, 0x70, 0x4d, 0x98, 0x22, 0x44, 0x5b, 0xf2, 0xac, 0x45, 0x8d,
	0x4b, 0x5a, 0x46, 0x44, 0x7d, 0x9b, 0x50, 0xfd, 0x19, 0x47, 0x83, 0xb4, 0x3b, 0xb4, 0x25, 0xea,
	0xee, 0x84, 0xd8, 0xf3, 0xb8, 0x38, 0x65, 0x5d, 0x77, 0x0a, 0x08, 0xc6, 0x52, 0x4a, 0x97, 0x15,
	0x63, 0x29, 0x9b, 0x36, 0x2c, 0xef, 0xe3, 0x05, 0x8b, 0xfd, 0x48, 0x77, 0x47, 0x62, 0x3a, 0x3f,
	0x01, 0x39, 0xc6, 0xe9, 0x7d, 0xbf, 0x87, 0xe4, 0x64, 0x8d, 0x42, 0x32, 0xc0, 0xf9, 0xd3, 0x02,
	0xfb, 0xd7, 0x18, 0xc3, 0xd4, 0xdd, 0x0f, 0xd3, 0xa3, 0xfe, 0x5d, 0x2e, 0x77, 0xa0, 0x29, 0x3d,
	0x74, 0xd8, 0x00, 0x8f, 0x46, 0x7d, 0xbc, 0x91, 0x7e, 0xcb, 0x6e, 0x01, 0x4d, 0xdb, 0x46, 0x20,
	0x5d, 0xef, 0x77, 0xc5, 0x58, 0xd9, 0xcd, 0x83, 0xce, 0x5f, 0x16, 0x6c, 0x15, 0x52, 0x48, 0x3e,
	0x93, 0x24, 0x11, 0xf3, 0x4b, 0x52, 0xa9, 0x64, 0x5f, 0xd2, 0x33, 0x68, 0x88, 0x8d, 0x59, 0x2e,
	0x25, 0x15, 0x24, 0x07, 0x26, 0xdf, 0x70, 0x9a, 0x89, 0x4a, 0x38, 0x87, 0x39, 0x97, 0xf0, 0x54,
	0xe6, 0xe1, 0x62, 0x0f, 0x47, 0x91, 0x3f, 0xc3, 0xf0, 0x4c, 0x24, 0xeb, 0x3e, 0x91, 0x4a, 0x73,
	0x22, 0x51, 0x78, 0x74, 0x88, 0x51, 0x37, 0xc2, 0xf1, 0x49, 0x3c, 0x3c, 0xc7, 0xd0, 0x20, 0x7c,
	0xde, 0xc5, 0xe5, 0x78, 0xb0, 0x21, 0x33, 0xeb, 0xc4, 0x61, 0xef, 0x92, 0x71, 0x34, 0x4f, 0xe8,
	0x8c, 0x1b, 0xea, 0xab, 0x2d, 0xd9, 0x76, 0x05, 0x42, 0x32, 0x40, 0xd0, 0x59, 0x20, 0x22, 0xb5,
	0x9d, 0x3f, 0xe0, 0x89, 0x0c, 0x25, 0x85, 0xb1, 0xc8, 0x80, 0xa1, 0x9f, 0x56, 0x5e, 0x3f, 0x1f,
	0xee, 0x14, 0x3a, 0x50, 0x33, 0x2f, 0x72, 0x7d, 0x39, 0x2b, 0xaa, 0xe7, 0x5c, 0xce, 0xa5, 0xdc,
	0xe5, 0x2c, 0xbe, 0x4d, 0xa1, 0x15, 0xba, 0xd1, 0xe5, 0xd8, 0xf9, 0x0d, 0x36, 0x0a, 0x6c, 0x3f,
	0x88, 0xfb, 0xb2, 0x76, 0x4f, 0xe1, 0xd1, 0x5b, 0x0f, 0x27, 0xea, 0xa2, 0x8c, 0xfd, 0xe8, 0xae,
	0xc3, 0x7c, 0x67, 0xc1, 0x5a, 0xb6, 0x41, 0x65, 0xd2, 0x82, 0x32, 0xbf, 0xf2, 0xf5, 0x42, 0x31,
	0x14, 0x91, 0xf6, 0x02, 0x9f, 0xdb, 0x25, 0x75, 0xa1, 0x88, 0x31, 0xf9, 0x18, 0x6a, 0x6e, 0x30,
	0xe1, 0x3a, 0x03, 0xa1, 0x7a, 0x75, 0x9a, 0x00, 0x6e, 0x3a, 0x65, 0x94, 0xb5, 0xb4, 0xa8, 0xac,
	0x4a, 0xfe, 0x49, 0xb3, 0x93, 0x39, 0x16, 0xcd, 0xe1, 0x06, 0x93, 0xb7, 0xcc, 0x8f, 0xc5, 0x55,
	0x22, 0x6f, 0xad, 0xc4, 0xde, 0xfd, 0x67, 0x19, 0xea, 0xdd, 0x4b, 0x16, 0x4a, 0x3d, 0x26, 0xbb,
	0x50, 0x4f, 0xdf, 0x5e, 0x64, 0x9d, 0x16, 0x5f, 0x86, 0x6d, 0x42, 0x67, 0x9f, 0x66, 0x9f, 0x43,
	0x2d, 0x79, 0xd1, 0x90, 0x16, 0x2d, 0xbc, 0xa3, 0xda, 0xeb, 0xb4, 0xf8, 0xdc, 0x21, 0x9f, 0x40,
	0x55, 0x47, 0x68, 0xd2, 0xbc, 0xfb, 0x35, 0x5a, 0xf0, 0xbd, 0x03, 0x15, 0xe5, 0xb8, 0x41, 0x73,
	0x5e, 0x9b, 0x34, 0xef, 0xf2, 0x53, 0x58, 0xed, 0xb2, 0x6b, 0x4c, 0x9a, 0x9b, 0xb4, 0x68, 0xa1,
	0xcf, 0xdb, 0x75, 0x9a, 0x2e, 0xfe, 0x02, 0x9a, 0xfb, 0xe8, 0x63, 0x94, 0x2d, 0xff, 0x80, 0xce,
	0xaa, 0xaf, 0xb9, 0xe3, 0x85, 0xb8, 0xda, 0xc5, 0x0e, 0x75, 0x3b, 0xdf, 0xb5, 0xfc, 0x6b, 0x78,
	0x7c, 0x36, 0xee, 0xb3, 0x2c, 0xc0, 0x9b, 0x6b, 0x0c, 0x27, 0xa1, 0x17, 0xe1, 0xed, 0x89, 0x7d,
	0x09, 0x1b, 0xb3, 0xfb, 0x7c, 0x36, 0xbd, 0x7d, 0xd7, 0x57, 0xd0, 0xc8, 0x69, 0x2d, 0x79, 0x42,
	0x17, 0xc9, 0xbf, 0xb9, 0xed, 0x1b, 0x2d, 0x40, 0x62, 0xd9, 0xab, 0x5e, 0x2f, 0x0e, 0x59, 0x84,
	0xf7, 0x22, 0xe3, 0x35, 0x3c, 0x5e, 0xa0, 0xed, 0xe4, 0x23, 0x7a, 0xbb, 0xea, 0x9b, 0x6e, 0x5e,
	0xe9, 0xf8, 0x45, 0x69, 0x26, 0x1f, 0xd2, 0xdb, 0x24, 0xdb, 0x74, 0xf1, 0x1d, 0x90, 0x59, 0x61,
	0x23, 0x6d, 0xba, 0x50, 0xed, 0xcc, 0xcd, 0xdf, 0x43, 0x23, 0x27, 0x21, 0x64, 0x83, 0xce, 0x13,
	0xf0, 0xf6, 0x26, 0x9d, 0xaf, 0x34, 0x2f, 0xa1, 0x99, 0x17, 0x70, 0xb2, 0x49, 0xe7, 0x2a, 0xba,
	0x19, 0xf4, 0x5b, 0x68, 0xe4, 0x84, 0x85, 0x6c, 0xd0, 0x79, 0x42, 0xd3, 0x6e, 0xd1, 0x82, 0x9c,
	0x9c, 0x57, 0xe5, 0xff, 0xda, 0xcb, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x8e, 0xe6, 0xf3,
	0xbd, 0x0d, 0x00, 0x00,
}
