// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "铭数区块链",
            "email": "liweihang@mingbyte.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/querySql": {
            "post": {
                "description": "根据sql语句查询对应结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据"
                ],
                "summary": "查询sql语句",
                "parameters": [
                    {
                        "description": "根据sql查询结果",
                        "name": "searchSql",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SearchSql"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询结果集，包括flowID、txID",
                        "schema": {
                            "$ref": "#/definitions/model.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "status bad request"
                }
            }
        },
        "model.SearchResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int32",
                    "example": 200
                },
                "flowId": {
                    "type": "string",
                    "format": "string"
                },
                "message": {
                    "type": "string",
                    "format": "string",
                    "example": "Search Success"
                },
                "txId": {
                    "type": "string",
                    "format": "string"
                }
            }
        },
        "model.SearchSql": {
            "type": "object",
            "properties": {
                "consumerId": {
                    "type": "string",
                    "format": "string",
                    "example": "202009021838"
                },
                "dumpId": {
                    "type": "string"
                },
                "providerId": {
                    "type": "string",
                    "format": "string",
                    "example": "202009021840"
                },
                "sql": {
                    "type": "string",
                    "format": "string",
                    "example": "select * from t_aos;"
                },
                "text": {
                    "type": "string",
                    "format": "string",
                    "example": "美国国家科学院"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:10086",
	BasePath:    "/datashare",
	Schemes:     []string{},
	Title:       "DataShare Api",
	Description: "铭数数据共享平台v1.0 Api",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
